### ISSUE TITLE
can implement mybatis-script with other template engine

### ISSUE THREAD

**Issue by stepjacky** [mybatis/freemarker-scripting#38]
I want to implement the mybatis-script with other template engine,how can i archive to ,
has any instructions doc?

**Comment by mnesarco** [comment]
Just implement: org.apache.ibatis.scripting.LanguageDriver
There are three scripting drivers already implemented and you can use them as a guide.

https://github.com/mybatis/freemarker-scripting

https://github.com/mybatis/velocity-scripting

https://github.com/mybatis/mybatis-3/blob/master/src/main/java/org/apache/ibatis/scripting/xmltags/XMLLanguageDriver.java

**Comment by stepjacky** [comment]
thks  i got  it
