### ISSUE TITLE
While by default #{...} is interpreted, that can be disabled by setting the interpolation_syntax configuration setting (Configuration.setInterpolationSyntax in the Java API) to dollar. Then #{...} will be just static text, and only ${...} will operate as interpolation.

### ISSUE THREAD

**Issue by qshun** [mybatis/freemarker-scripting#43]
[#{...}  can be disabled](https://freemarker.apache.org/docs/ref_depr_numerical_interpolation.html)

**Comment by kazuki43zoo** [comment]
Hi @qshun ,

Sorry for later reply.
Could you explain about actual problem? If possible, please provide the small reproduce project via GitHub? Do you want to specify the `#{...}`(MyBatis's standard bind variable) in your SQL query as follow?

**Comment by kazuki43zoo** [comment]
@qshun 

Since 1.2 (not released yet), we support configuration properties for customizing a template engine behavior via #51. Could you resolve this issue using 1.2.0-SNAPSHOT? If there is time, please try it and feedback to us.

**Comment by qshun** [comment]
this  issue resolved using 1.2.0-SNAPSHOT

**Comment by kazuki43zoo** [comment]
Fix via #51 .

**Comment by qshun** [comment]
my English is pool,could you disable interpret #{...} by default?

**Comment by kazuki43zoo** [comment]
Default behavior does not change. If you want to disable `#{...}`, please configure FreeMarker setting using configuration property.

* mybatis-freemarker.properties

```properties
freemarker-settings.interpolation_syntax=dollar
```
